name: jCustomPortals
version: 1.0.3
main: jcraft.customportals.MainClass
author: Kodek
depend: [WorldEdit]

commands:
   jportal:
      permission: jportal.admin
permissions:
   jportal.admin:
      default: op
      children:
         jportal.createportal: true
         jportal.createdest: true
         jportal.infodest: true
         jportal.infoportal: true
         jportal.modifydest: true
         jportal.modifyportal: true
         jportal.teleportdest: true
         jportal.listdest: true
         jportal.listportal: true
         jportal.teleport.*: true
   jportal.createportal:
      default: false
   jportal.createdest:
      default: false
   jportal.infodest:
      default: false
   jportal.infoportal:
      default: false
   jportal.modifydest:
      default: false
   jportal.modifyportal:
      default: false
   jportal.teleportdest:
      default: false
   jportal.listdest:
      default: false
   jportal.listportal:
      default: false
   jportal.teleport.*:
      default: false